version: '2'

services:
    myapp:
        container_name: myapp
        build:
            context: .
            dockerfile: Dockerfile
        image: myapp:latest
        ports:
            - 8080:8080
        networks:
          - internal-network
        depends_on:
            elastic:
                condition: service_healthy

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        container_name: elastic
        environment:
          - discovery.type=single.node
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - data01:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
          - 9300:9300
        networks:
          - internal-network
        healthcheck:
            test: ["CMD", "curl", "http://localhost:9200"]
            interval: 3s
            timeout: 2s
            retries: 10

volumes:
    data01:
        driver: local
        
networks:
    internal-network:
        driver: bridge